remote-theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Cyberme0w's Digital Home
description: A digital collection of bits and pieces of my adventure into the digital realm.

